#!/usr/bin/env node
// Reads owned state + history, prints a table and (with --write) regenerates status.md.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const p = (...a) => path.join(ROOT, ...a);
const WRITE = process.argv.includes('--write');
const TZ = process.env.NYZ_TZ || 'America/Toronto';

const cfg = JSON.parse(fs.readFileSync(p('sites.json'), 'utf8'));
const state = fs.existsSync(p('state.json')) ? JSON.parse(fs.readFileSync(p('state.json'), 'utf8')) : {};
const sites = cfg.sites.filter(s => s.enabled !== false);

// Load recent history rows (current + previous month is plenty for a 30d window).
const rows = [];
if (fs.existsSync(p('history'))) {
  for (const f of fs.readdirSync(p('history')).filter(f => f.endsWith('.jsonl')).sort().slice(-2)) {
    for (const line of fs.readFileSync(p('history', f), 'utf8').split('\n')) {
      if (!line.trim()) continue;
      try { rows.push(JSON.parse(line)); } catch { /* skip a torn line */ }
    }
  }
}

function uptime(domain, hours) {
  const cutoff = Date.now() - hours * 3600 * 1000;
  let total = 0, up = 0;
  for (const r of rows) {
    if (Date.parse(r.t) < cutoff) continue;
    const seen = (r.ms && domain in r.ms) || (r.down && domain in r.down);
    if (!seen) continue;
    total++;
    if (r.ms && domain in r.ms) up++;
  }
  return total ? { pct: (up / total) * 100, total } : null;
}

function avgMs(domain, hours) {
  const cutoff = Date.now() - hours * 3600 * 1000;
  let sum = 0, n = 0;
  for (const r of rows) {
    if (Date.parse(r.t) < cutoff) continue;
    if (r.ms && domain in r.ms) { sum += r.ms[domain]; n++; }
  }
  return n ? Math.round(sum / n) : null;
}

const pct = u => (u === null ? '—' : `${u.pct.toFixed(u.pct >= 99.95 ? 0 : 2)}%`);
const fmtDur = ms => {
  const m = Math.round(ms / 60000);
  if (m < 60) return `${m}m`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h`;
  return `${Math.floor(h / 24)}d`;
};

const table = sites.map(s => {
  const st = state[s.domain] || {};
  const u24 = uptime(s.domain, 24), u7 = uptime(s.domain, 24 * 7), u30 = uptime(s.domain, 24 * 30);
  return {
    domain: s.domain,
    label: s.label || s.domain,
    status: st.status || 'unknown',
    detail: st.status === 'down' ? st.reason : (st.lastMs != null ? `${st.lastMs}ms` : '—'),
    since: st.since ? fmtDur(Date.now() - Date.parse(st.since)) : '—',
    u24: pct(u24), u7: pct(u7), u30: pct(u30),
    avg: avgMs(s.domain, 24 * 7),
    cert: st.cert?.daysLeft ?? null,
  };
});

const down = table.filter(r => r.status === 'down');
const up = table.filter(r => r.status === 'up');
const icon = s => (s === 'up' ? '🟢' : s === 'down' ? '🔴' : '⚪️');
// Emoji render two columns wide in a terminal but count as one .length unit.
const padStatus = (s, w = 12) => (icon(s) + ' ' + s).padEnd(w + (icon(s).length - 1));

// terminal
console.log(`\nNYZ Uptime — ${up.length} up / ${down.length} down / ${table.length - up.length - down.length} unknown · ${rows.length} checks on record\n`);
console.log('  ' + 'DOMAIN'.padEnd(30) + 'STATUS'.padEnd(12) + '24h'.padEnd(9) + '7d'.padEnd(9) + '30d'.padEnd(9) + 'SSL');
for (const r of table) {
  console.log('  ' + r.domain.padEnd(30) +
    padStatus(r.status) +
    r.u24.padEnd(9) + r.u7.padEnd(9) + r.u30.padEnd(9) +
    (r.cert === null ? '—' : `${r.cert}d`) +
    (r.status === 'down' ? `   ← ${r.detail} for ${r.since}` : ''));
}
console.log('');

if (WRITE) {
  const stamp = new Intl.DateTimeFormat('en-CA', {
    timeZone: TZ, dateStyle: 'medium', timeStyle: 'short', hour12: false,
  }).format(new Date());
  const md = [
    '# NYZ Uptime — Status',
    '',
    `**${up.length}/${table.length} sites up**${down.length ? ` · **${down.length} down**` : ''} · last checked ${stamp} (${TZ})`,
    '',
    down.length
      ? `> 🔴 **Down now:** ${down.map(r => `\`${r.domain}\` (${r.detail}, ${r.since})`).join(' · ')}`
      : (up.length === table.length ? '> 🟢 All sites responding.' : '> ⚪️ No checks recorded yet — run `npm run check` or trigger the workflow.'),
    '',
    '| Site | Status | 24h | 7d | 30d | Avg (7d) | SSL |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: |',
    ...table.map(r => `| [${r.domain}](https://${r.domain}) | ${icon(r.status)} ${r.status === 'down' ? `down — ${r.detail}` : r.status} | ${r.u24} | ${r.u7} | ${r.u30} | ${r.avg ? r.avg + 'ms' : '—'} | ${r.cert === null ? '—' : r.cert + 'd'} |`),
    '',
    '<sub>Generated by `report.js`. Source of truth: `state.json` + `history/`. Alerts go to Telegram.</sub>',
    '',
  ].join('\n');
  fs.writeFileSync(p('status.md'), md);
  console.log('wrote status.md');
}
